---
version: '2'
services:
  worker:
    extends:
      service: common
    links:
    - redis
    - db
    depends_on:
    - redis
    - db
    command: bundle exec rake jobs:work
  common:
    build: "."
    environment:
      DATABASE_URL: postgres://postgres:yX634jPgRnJk4fyVfKH2cg@db:5432/postgres
      RACK_ENV: production
  app:
    extends:
      service: common
    command: bundle exec puma -C config/puma.rb
    links:
    - db
    ports:
    - 3000:3000
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: yX634jPgRnJk4fyVfKH2cg
